#Docker compose para desarrollo
#Importante darle permisos de escrituras a la carpetas donde se guardan los archivos temporales manualmente
version: "3.9"

services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: usuario
      MYSQL_USER: anghel3m
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - .db:/var/lib/mysql
      - ./config/db/usuarios.sql:/docker-entrypoint-initdb.d/init.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 9091:80
  web: 
    container_name: dataFis #Nombre del contenedor
    image: oberd/php-8.1-apache
    ports:
      - 9090:80 #Puerto de la maquina : puerto del contenedor
    volumes:
      - .:/var/www/html/ #Carpeta de la maquina : carpeta del contenedor
      # - ./php.ini:/usr/local/etc/php/php.ini #Archivo de configuracion de php
    links:
     - db